export const PROJECT_CREATE_REQUEST = 'PROJECT_CREATE_REQUEST'
export const PROJECT_CREATE_SUCCESS = 'PROJECT_CREATE_SUCCESS'
export const PROJECT_CREATE_FAILURE = "PROJECT_CREATE_FAILURE"
export const PROJECT_CREATE_RESET = "PROJECT_CREATE_RESET"

export const PROJECT_DETAIL_REQUEST = "PROJECT_DETAIL_REQUEST";
export const PROJECT_DETAIL_SUCCESS = "PROJECT_DETAIL_SUCCESS";
export const PROJECT_DETAIL_FAILURE = "PROJECT_DETAIL_FAILURE";

export const PROJECT_LIST_REQUEST = "PROJECT_LIST_REQUEST";
export const PROJECT_LIST_SUCCESS = "PROJECT_LIST_SUCCESS";
export const PROJECT_LIST_FAILURE = "PROJECT_LIST_FAILURE";

export const PROJECT_UPDATE_REQUEST = "PROJECT_UPDATE_REQUEST";
export const PROJECT_UPDATE_SUCCESS = "PROJECT_UPDATE_SUCCESS";
export const PROJECT_UPDATE_FAILURE = "PROJECT_UPDATE_FAILURE";
export const PROJECT_UPDATE_RESET = "PROJECT_UPDATE_RESET";

export const PROJECT_REMARK_DESTROY_REQUEST = "PROJECT_REMARK_DESTROY_REQUEST";
export const PROJECT_REMARK_DESTROY_SUCCESS = "PROJECT_REMARK_DESTROY_SUCCESS";
export const PROJECT_REMARK_DESTROY_FAILURE = "PROJECT_REMARK_DESTROY_FAILURE";
export const PROJECT_REMARK_DESTROY_RESET = "PROJECT_REMARK_DESTROY_RESET";

export const PROJECT_REMARK_CREATE_REQUEST = "PROJECT_REMARK_CREATE_REQUEST";
export const PROJECT_REMARK_CREATE_SUCCESS = "PROJECT_REMARK_CREATE_SUCCESS";
export const PROJECT_REMARK_CREATE_FAILURE = "PROJECT_REMARK_CREATE_FAILURE";
export const PROJECT_REMARK_CREATE_RESET = "PROJECT_REMARK_CREATE_RESET";

export const PROJECT_DESTROY_REQUEST = "PROJECT_DESTROY_REQUEST";
export const PROJECT_DESTROY_SUCCESS = "PROJECT_DESTROY_SUCCESS";
export const PROJECT_DESTROY_FAILURE = "PROJECT_DESTROY_FAILURE";
export const PROJECT_DESTROY_RESET = "PROJECT_DESTROY_RESET";