export const TASK_CREATE_REQUEST = 'TASK_CREATE_REQUEST'
export const TASK_CREATE_SUCCESS = 'TASK_CREATE_SUCCESS'
export const TASK_CREATE_FAILURE = "TASK_CREATE_FAILURE";
export const TASK_CREATE_RESET = "TASK_CREATE_RESET";

export const TASK_DETAIL_REQUEST = "TASK_DETAIL_REQUEST";
export const TASK_DETAIL_SUCCESS = "TASK_DETAIL_SUCCESS";
export const TASK_DETAIL_FAILURE = "TASK_DETAIL_FAILURE";

export const TASK_LIST_REQUEST = "TASK_LIST_REQUEST";
export const TASK_LIST_SUCCESS = "TASK_LIST_SUCCESS";
export const TASK_LIST_FAILURE = "TASK_LIST_FAILURE";

export const TASK_DESTROY_REQUEST = "TASK_DESTROY_REQUEST";
export const TASK_DESTROY_SUCCESS = "TASK_DESTROY_SUCCESS";
export const TASK_DESTROY_FAILURE = "TASK_DESTROY_FAILURE";
export const TASK_DESTROY_RESET = "TASK_DESTROY_RESET";

export const TASK_REMARK_CREATE_REQUEST = "TASK_REMARK_CREATE_REQUEST";
export const TASK_REMARK_CREATE_SUCCESS = "TASK_REMARK_CREATE_SUCCESS";
export const TASK_REMARK_CREATE_FAILURE = "TASK_REMARK_CREATE_FAILURE";
export const TASK_REMARK_CREATE_RESET = "TASK_REMARK_CREATE_RESET";

export const TASK_REMARK_DESTROY_REQUEST = "TASK_REMARK_DESTROY_REQUEST";
export const TASK_REMARK_DESTROY_SUCCESS = "TASK_REMARK_DESTROY_SUCCESS";
export const TASK_REMARK_DESTROY_FAILURE = "TASK_REMARK_DESTROY_FAILURE";
export const TASK_REMARK_DESTROY_RESET = "TASK_REMARK_DESTROY_RESET";

export const TASK_UPDATE_REQUEST = "TASK_UPDATE_REQUEST";
export const TASK_UPDATE_SUCCESS = "TASK_UPDATE_SUCCESS";
export const TASK_UPDATE_FAILURE = "TASK_UPDATE_FAILURE";
export const TASK_UPDATE_RESET = "TASK_UPDATE_RESET";

export const TASK_USER_LIST_REQUEST = 'TASK_USER_LIST_REQUEST'
export const TASK_USER_LIST_SUCCESS = 'TASK_USER_LIST_SUCCESS'
export const TASK_USER_LIST_FAILURE = "TASK_USER_LIST_FAILURE";